/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Eszti
 */
public class PlaceTroops extends javax.swing.JDialog {

    private int numberOfPlacedTroops;
    /**
     * Creates new form PlaceTroops
     */
    public PlaceTroops(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        numberOfPlacedTroops = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSliderNumberOfTroops = new javax.swing.JSlider();
        jButtonPlace = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setTitle("Place troops");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setText("Number of troops:");

        jSliderNumberOfTroops.setMajorTickSpacing(1);
        jSliderNumberOfTroops.setMaximum(10);
        jSliderNumberOfTroops.setMinimum(1);
        jSliderNumberOfTroops.setMinorTickSpacing(1);
        jSliderNumberOfTroops.setPaintLabels(true);
        jSliderNumberOfTroops.setPaintTicks(true);
        jSliderNumberOfTroops.setValue(1);

        jButtonPlace.setText("Place");
        jButtonPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlaceActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSliderNumberOfTroops, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonPlace)
                .addGap(69, 69, 69)
                .addComponent(jButtonCancel)
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jSliderNumberOfTroops, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPlace)
                    .addComponent(jButtonCancel))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlaceActionPerformed
        numberOfPlacedTroops = jSliderNumberOfTroops.getValue();
        setVisible(false);
    }//GEN-LAST:event_jButtonPlaceActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        numberOfPlacedTroops = 0;
        this.jSliderNumberOfTroops.setValue(this.jSliderNumberOfTroops.getMinimum());
    }//GEN-LAST:event_formComponentShown
    
    public void setRange(int min, int max)
    {
        jSliderNumberOfTroops.setMinimum(min);
        jSliderNumberOfTroops.setMaximum(max);
    }
    
    public int getNumberOfPlacedTroops()
    {
        return numberOfPlacedTroops;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonPlace;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSlider jSliderNumberOfTroops;
    // End of variables declaration//GEN-END:variables
}
