/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Eszter
 */
public class PlayerDefeated extends javax.swing.JDialog {

    /**
     * Creates new form PlayerDefeated
     */
    public PlayerDefeated() {
        initComponents();
    }
    
    public PlayerDefeated(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabelPlayerDefeated = new javax.swing.JLabel();

        setTitle("Player is defeated");
        setPreferredSize(new java.awt.Dimension(370, 127));
        setResizable(false);
        setSize(new java.awt.Dimension(370, 127));

        jButton1.setText("Ok");

        jLabelPlayerDefeated.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPlayerDefeated.setText("Nobody is defeated.");
        jLabelPlayerDefeated.setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelPlayerDefeated, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(142, 142, 142))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelPlayerDefeated)
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelPlayerDefeated;
    // End of variables declaration//GEN-END:variables

    public void setText(String playerName)
    {
        this.jLabelPlayerDefeated.setText(String.format("%s is defeated.", playerName));
    }

}
